---
title: "Ejemplo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(magrittr)
library(data.table)
library(metR)

source("preparar-datos.R")    # funciones para descargar y cargar los datos
```


## La precipitación en sudamerica

```{r precip}
precip <- datos_pp_field()

precip_anom <- precip %>% 
  .[, .(precip = mean(precip)), by = .(time = seasonally(time))] %>% 
  .[, precip_anomalia := precip - mean(precip), by = .(season(time))]
precip_anom[, clase := sign(precip_anomalia)]
```


```{r}
precip %>% 
  .[, mean_precip := mean(precip), by = .(lon, lat)] %>% 
  .[time == unique(time)[10]] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = precip)) +
  geom_polygon(data = map_data("world2"),
               aes(long, lat, group = group), 
               fill = NA, color = "black", size = 0.1) +
  annotate("rect", xmin = 299.26, xmax = 312, ymin = -34.6, 
           ymax = -24, 
           colour = "black", fill = NA)  +
  scale_fill_distiller(palette = "YlGnBu",
                       direction = 1) +
  # scale_fill_divergent(guide= "none") +
  scale_x_longitude() +
  scale_y_latitude() +
  coord_quickmap(xlim = c(270, 330), y = c(-60, 20)) +
  labs(title = "Precipitación mensual",
       subtitle = "Octubre de 1979",
       fill = NULL) +
  theme_minimal()
```

```{r}
precip %>% 
  .[, mean_precip := mean(precip), by = .(lon, lat)] %>% 
  .[time == unique(time)[10]] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = precip - mean_precip)) +
  geom_polygon(data = map_data("world2"),
               aes(long, lat, group = group), 
               fill = NA, color = "black", size = 0.1) +
  annotate("rect", xmin = 299.26, xmax = 312, ymin = -34.6, 
           ymax = -24, 
           colour = "black", fill = NA)  +
  scale_fill_gradient2(low = "#f37329", high = "#68b723",
                       limits = c(-5, 5), oob = scales::squish) +
  scale_x_longitude() +
  scale_y_latitude() +
  coord_quickmap(xlim = c(270, 330), y = c(-60, 20)) +
  labs(title = "Anomalía de precipitación",
       subtitle = "Octubre de 1979",
       fill = NULL) +
  theme_minimal()
```


Datos de precipitación trimestral en el Sudeste de Sudamétrica. 

```{r pp-SESA}
precip <- datos_precip() %>% 
  .[, .(precip = mean(precip)), by = .(time = seasonally(time))] %>% 
  .[, precip_anomalia := precip - mean(precip), by = .(season(time))]
precip[, clase := sign(precip_anomalia)]

ggplot(precip, aes(time, precip_anomalia)) +
  geom_col(aes(fill = factor(clase))) +
  scale_fill_manual(values = c("-1" = "#f37329", 
                               "1" = "#68b723"), 
                    guide = "none") +
  scale_y_continuous("Anomalía trimestral de precipitación") +
  scale_x_date(NULL) +
  theme_minimal()
```


```{r sst}
sst <- datos_sst() %>%
  na.omit() %>%
  .[, .(t = mean(t)), by = .(lon, lat, time = seasonally(time))] %>% 
  .[, t_anomaly := t - mean(t), by = .(lon, lat, season(time))] %>% 
  .[, t_anomaly_sd := t_anomaly/sd(t_anomaly)] %>%
  .[, id := interaction(lon, lat)]  %>%
  .[order(as.numeric(id))]

```

```{r campo-sst}
sst %>% 
  .[time == time[1]] %>% 
   ggplot(aes(lon, lat)) +
  # geom_contour_fill(aes(z = t_anomaly)) +
  geom_tile(aes(fill = t_anomaly), color = "grey90", size = 0.005) +
  geom_polygon(data = map_data("world2"),
               aes(long, lat, group = group), 
               fill = "white", color = "black", size = 0.1) +
  annotate("rect", xmin = 299.26, xmax = 312, ymin = -34.6, 
           ymax = -24, 
           colour = "black", fill = NA)  +
  scale_fill_divergent(guide= "none") +
  scale_x_longitude() +
  scale_y_latitude() +
  ggtitle("Temperatura de la superficie del mar") +
  coord_quickmap() 
```
